### PR TITLE
fix: manage accounts qa

### LINKED ISSUE #932: Manage Accounts improvements
### Code review improvements
- [x] Unit tests on `store.catalog.ts`
- [x] Attempt to reduce `find`s inside loops in the store
- [x] Refactor store to remove static methods shared with UI

### Usability & Sentinels feedback improvements
- [x] Redo account actions dropdown 
  - [x] Move to sidebar (https://github.com/TalismanSociety/talisman/issues/811)
  - [x] Add 'Manage accounts` as first option, even when no account selected
  - [x] Remove `Add custom token` option
- [x] Fix folder open/close UX
  - [x] Always show chevron & three dots menu
  - [x] Show empty dropzone for empty folders
- [x] Investigate Ramo's bug with account balances in folder

### PR DESCRIPTION
**Pull request by alecdwm**
Closes https://github.com/TalismanSociety/talisman/issues/932, https://github.com/TalismanSociety/talisman/issues/811

### CODE REVIEW

File: apps/extension/src/ui/apps/dashboard/routes/Portfolio/AccountContextMenu.tsx [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+
+  const { canRemoveFunc, open: _openAccountRemoveModal } = useAccountRemoveModal()
+  const canRemove = useMemo(() => canRemoveFunc(account), [account, canRemoveFunc])
+  const openAccountRemoveModal = useCallback(
+    () => _openAccountRemoveModal(account),
+    [_openAccountRemoveModal, account]
+  )
+
+  return (
+    <ContextMenu placement="bottom-end">
```
Comment (0xKheops) [inline apps/extension/src/ui/apps/dashboard/routes/Portfolio/AccountContextMenu.tsx]: as button is on the left side of the screen, it feels weird if menu opens towards the left

```suggestion
    <ContextMenu placement="bottom-start">
```

**Review by chidg — APPROVED** [review]
LGTM!
