### PR TITLE
fix: manage accounts design/ux improvements

### LINKED ISSUE #1046: [Enhancement] Manage Accounts - Optimize chevron position
1. Move Chevron position
2. Move account selector drag handle
(See Figma)

### LINKED ISSUE #1188: [Enhancement] Manage Accounts - Wording change
**Describe the bug**
It is unclear what the checbox is referring to

**Expected behaviour**
Change "followed only" to "Create folder inside my follow only accounts"

**Screenshots**
If applicable, add screenshots/recordings to help explain your problem.

image

### PR DESCRIPTION
**Pull request by alecdwm**
Fixes https://github.com/TalismanSociety/talisman/issues/1046, https://github.com/TalismanSociety/talisman/issues/1188

<div align="center">

before
**before**

after
**after**

</div>

### CODE REVIEW

File: apps/extension/src/ui/apps/dashboard/routes/Settings/Accounts/TreeItem.tsx [hunk 1]
```diff
@@ -64,38 +64,42 @@ export const TreeAccountItem = forwardRef<HTMLDivElement, Props & { item: UiTree
...
-          />
-          <div className="flex grow flex-col gap-2 overflow-hidden">
-            <div className="flex items-center gap-2">
-              <div className="overflow-hidden text-ellipsis whitespace-nowrap">{account.name}</div>
-              <AccountTypeIcon className="text-primary" origin={account.origin} />
+        <div ref={ref} className="relative flex items-center gap-8" style={style}>
+          <div
+            className={classNames(
+              "bg-black-secondary flex flex-grow items-center gap-8 rounded-sm border-[1px] border-transparent p-8",
+              depth === 0 && "pl-24",
```
Comment (0xKheops) [inline apps/extension/src/ui/apps/dashboard/routes/Settings/Accounts/TreeItem.tsx:71]: need to add `overflow-hidden` on lines 70 and 153 to prevent the grid rows to go larger than the table

**Review by 0xKheops — CHANGES_REQUESTED** [review]
Nice one, just a lil glitch to fix for very long account or folder names

File: apps/extension/src/ui/apps/dashboard/routes/Settings/Accounts/TreeItem.tsx (hunk 1 above)
Comment (alecdwm) [reply apps/extension/src/ui/apps/dashboard/routes/Settings/Accounts/TreeItem.tsx:71]: Oh good catch!

**Review by 0xKheops — APPROVED** [review]
LGTM! :+1:
